name       : libadwaita
version    : 1.2.0
release    : 3
source     :
    - https://download.gnome.org/sources/libadwaita/1.2/libadwaita-1.2.0.tar.xz : 322f3e1be39ba67981d9fe7228a85818eccaa2ed0aa42bcafe263af881c6460c
license    : LGPL-2.1-only # CHECK ME
component  : desktop.library
summary    : Building blocks for modern adaptive GNOME applications.
description: |
    Building blocks for modern adaptive GNOME applications.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - sassc
    - vala

setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
