name       : libadwaita
version    : 1.1.4
release    : 2
source     :
    - https://download.gnome.org/sources/libadwaita/1.1/libadwaita-1.1.4.tar.xz : fcc6d56669d33ac3d030098d7571d8045a02e18dc083b49a5a5a6325068e6b58
license    : LGPL-2.1-only # CHECK ME
component  : desktop.library
summary    : Building blocks for modern adaptive GNOME applications.
description: |
    Building blocks for modern adaptive GNOME applications.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - sassc
    - vala

setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
