name       : libadwaita
version    : 1.1.0
release    : 1
source     :
    - https://download.gnome.org/sources/libadwaita/1.1/libadwaita-1.1.0.tar.xz : aff598803e810cc28266472cf5bf65e5ed5b90bb3523e206b06b14527325010e
license    : LGPL-2.1-only # CHECK ME
component  : desktop.library
summary    : Building blocks for modern adaptive GNOME applications.
description: |
    Building blocks for modern adaptive GNOME applications.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - sassc
    - vala

setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
