name       : libadwaita
version    : 1.3.2
release    : 6
source     :
    - https://download.gnome.org/sources/libadwaita/1.3/libadwaita-1.3.2.tar.xz : b38c91658b2d1fcb7eedf687858b0a54de39af6357661912b54271884c8e195e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Building blocks for modern adaptive GNOME applications.
description: |
    Building blocks for modern adaptive GNOME applications.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - sassc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
